# Generated by Django 5.1.4 on 2025-01-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scam_reports', '0003_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commented_by',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='user',
            new_name='reacted_by',
        ),
    ]
